// Built-in question bank - works for FREE with no API key needed
// Each category has multiple questions so games feel fresh

export interface BankQuestion {
  text: string
  optionA: string
  optionB: string
  optionC: string
  optionD: string
  correctAnswer: 'optionA' | 'optionB' | 'optionC' | 'optionD'
  timeLimit: number
}

export const questionBank: Record<string, BankQuestion[]> = {
  'Bible Quiz': [
    { text: 'Who was the first man created in the Bible?', optionA: 'Adam', optionB: 'Abraham', optionC: 'Noah', optionD: 'Moses', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who was the first woman in the Bible?', optionA: 'Sarah', optionB: 'Ruth', optionC: 'Eve', optionD: 'Mary', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'How many days did God take to create the world?', optionA: '5', optionB: '6', optionC: '7', optionD: '10', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who built the ark to survive the great flood?', optionA: 'Abraham', optionB: 'Moses', optionC: 'David', optionD: 'Noah', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What was the name of the garden where Adam and Eve lived?', optionA: 'Gethsemane', optionB: 'Eden', optionC: 'Canaan', optionD: 'Babylon', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who parted the Red Sea?', optionA: 'Joshua', optionB: 'Elijah', optionC: 'Moses', optionD: 'Aaron', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'How many apostles did Jesus choose?', optionA: '7', optionB: '10', optionC: '12', optionD: '15', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who betrayed Jesus for 30 pieces of silver?', optionA: 'Peter', optionB: 'Thomas', optionC: 'James', optionD: 'Judas Iscariot', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What is the first book of the Bible?', optionA: 'Exodus', optionB: 'Genesis', optionC: 'Leviticus', optionD: 'Matthew', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who killed Goliath with a sling and a stone?', optionA: 'Saul', optionB: 'Solomon', optionC: 'David', optionD: 'Samuel', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What fruit is traditionally associated with Adam and Eve\'s sin?', optionA: 'Fig', optionB: 'Apple', optionC: 'Grape', optionD: 'Pomegranate', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who was swallowed by a great fish?', optionA: 'Elijah', optionB: 'Jonah', optionC: 'Isaiah', optionD: 'Job', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the last book of the Bible?', optionA: 'Jude', optionB: 'Acts', optionC: 'Revelation', optionD: 'Hebrews', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Where was Jesus born?', optionA: 'Nazareth', optionB: 'Jerusalem', optionC: 'Bethlehem', optionD: 'Capernaum', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who was the oldest person in the Bible?', optionA: 'Noah', optionB: 'Abraham', optionC: 'Methuselah', optionD: 'Adam', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What did God give Moses on Mount Sinai?', optionA: 'The Ten Commandments', optionB: 'The Ark of the Covenant', optionC: 'A staff', optionD: 'A crown', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who was the first king of Israel?', optionA: 'David', optionB: 'Solomon', optionC: 'Saul', optionD: 'Samuel', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What did Jesus turn water into at the wedding at Cana?', optionA: 'Milk', optionB: 'Wine', optionC: 'Oil', optionD: 'Vinegar', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many plagues were sent upon Egypt?', optionA: '7', optionB: '8', optionC: '10', optionD: '12', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who was thrown into the lion\'s den?', optionA: 'Daniel', optionB: 'David', optionC: 'Ezekiel', optionD: 'Elijah', correctAnswer: 'optionA', timeLimit: 15 },
  ],
  'Science': [
    { text: 'What is the chemical symbol for water?', optionA: 'H2O', optionB: 'CO2', optionC: 'NaCl', optionD: 'O2', correctAnswer: 'optionA', timeLimit: 10 },
    { text: 'What planet is known as the Red Planet?', optionA: 'Venus', optionB: 'Mars', optionC: 'Jupiter', optionD: 'Saturn', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the powerhouse of the cell?', optionA: 'Nucleus', optionB: 'Ribosome', optionC: 'Mitochondria', optionD: 'Golgi body', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What gas do plants absorb from the atmosphere?', optionA: 'Oxygen', optionB: 'Nitrogen', optionC: 'Carbon dioxide', optionD: 'Hydrogen', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the speed of light approximately?', optionA: '300,000 km/s', optionB: '150,000 km/s', optionC: '500,000 km/s', optionD: '100,000 km/s', correctAnswer: 'optionA', timeLimit: 20 },
    { text: 'What is the hardest natural substance on Earth?', optionA: 'Gold', optionB: 'Iron', optionC: 'Diamond', optionD: 'Quartz', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the largest organ in the human body?', optionA: 'Heart', optionB: 'Liver', optionC: 'Brain', optionD: 'Skin', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'How many bones are in the adult human body?', optionA: '186', optionB: '206', optionC: '226', optionD: '256', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What element does the chemical symbol "Fe" represent?', optionA: 'Fluorine', optionB: 'Fermium', optionC: 'Iron', optionD: 'Francium', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the most abundant gas in Earth\'s atmosphere?', optionA: 'Oxygen', optionB: 'Carbon dioxide', optionC: 'Nitrogen', optionD: 'Argon', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What type of animal is a dolphin?', optionA: 'Fish', optionB: 'Reptile', optionC: 'Amphibian', optionD: 'Mammal', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What force keeps planets in orbit around the Sun?', optionA: 'Magnetism', optionB: 'Friction', optionC: 'Gravity', optionD: 'Inertia', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the pH of pure water?', optionA: '5', optionB: '7', optionC: '9', optionD: '10', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What part of the atom has a positive charge?', optionA: 'Electron', optionB: 'Neutron', optionC: 'Proton', optionD: 'Nucleus shell', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the boiling point of water in Celsius?', optionA: '90°C', optionB: '100°C', optionC: '110°C', optionD: '120°C', correctAnswer: 'optionB', timeLimit: 10 },
  ],
  'History': [
    { text: 'In what year did World War II end?', optionA: '1943', optionB: '1944', optionC: '1945', optionD: '1946', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who was the first President of the United States?', optionA: 'Thomas Jefferson', optionB: 'John Adams', optionC: 'Benjamin Franklin', optionD: 'George Washington', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What ancient civilization built the pyramids?', optionA: 'Roman', optionB: 'Greek', optionC: 'Egyptian', optionD: 'Persian', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'In what year did the Titanic sink?', optionA: '1910', optionB: '1912', optionC: '1914', optionD: '1916', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who painted the ceiling of the Sistine Chapel?', optionA: 'Leonardo da Vinci', optionB: 'Raphael', optionC: 'Michelangelo', optionD: 'Donatello', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What was the name of the ship the Pilgrims sailed on?', optionA: 'Mayflower', optionB: 'Santa Maria', optionC: 'Endeavour', optionD: 'Victoria', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who discovered America in 1492?', optionA: 'Vasco da Gama', optionB: 'Ferdinand Magellan', optionC: 'Christopher Columbus', optionD: 'Amerigo Vespucci', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What empire was ruled by Genghis Khan?', optionA: 'Roman Empire', optionB: 'Ottoman Empire', optionC: 'Mongol Empire', optionD: 'Byzantine Empire', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'In what year did the Berlin Wall fall?', optionA: '1987', optionB: '1988', optionC: '1989', optionD: '1991', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who was known as the "Iron Lady"?', optionA: 'Angela Merkel', optionB: 'Indira Gandhi', optionC: 'Margaret Thatcher', optionD: 'Golda Meir', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What country gave the Statue of Liberty to the USA?', optionA: 'England', optionB: 'Spain', optionC: 'Italy', optionD: 'France', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'Who was the leader of Nazi Germany?', optionA: 'Joseph Stalin', optionB: 'Benito Mussolini', optionC: 'Adolf Hitler', optionD: 'Hirohito', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What ancient city was destroyed by a volcanic eruption in 79 AD?', optionA: 'Athens', optionB: 'Rome', optionC: 'Pompeii', optionD: 'Carthage', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Which war was fought between the North and South in the USA?', optionA: 'Revolutionary War', optionB: 'War of 1812', optionC: 'Civil War', optionD: 'Spanish-American War', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who wrote the Declaration of Independence?', optionA: 'George Washington', optionB: 'Benjamin Franklin', optionC: 'Alexander Hamilton', optionD: 'Thomas Jefferson', correctAnswer: 'optionD', timeLimit: 15 },
  ],
  'Geography': [
    { text: 'What is the largest continent by area?', optionA: 'Africa', optionB: 'North America', optionC: 'Europe', optionD: 'Asia', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the longest river in the world?', optionA: 'Amazon', optionB: 'Nile', optionC: 'Mississippi', optionD: 'Yangtze', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the smallest country in the world?', optionA: 'Monaco', optionB: 'San Marino', optionC: 'Vatican City', optionD: 'Liechtenstein', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What ocean is the largest?', optionA: 'Atlantic', optionB: 'Indian', optionC: 'Arctic', optionD: 'Pacific', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the capital of Australia?', optionA: 'Sydney', optionB: 'Melbourne', optionC: 'Canberra', optionD: 'Brisbane', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Mount Everest is located in which mountain range?', optionA: 'Andes', optionB: 'Alps', optionC: 'Rockies', optionD: 'Himalayas', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What country has the most people?', optionA: 'USA', optionB: 'India', optionC: 'Indonesia', optionD: 'Brazil', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the largest desert in the world?', optionA: 'Sahara', optionB: 'Antarctic', optionC: 'Gobi', optionD: 'Arabian', correctAnswer: 'optionB', timeLimit: 20 },
    { text: 'What country is shaped like a boot?', optionA: 'Greece', optionB: 'Portugal', optionC: 'Italy', optionD: 'Croatia', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the capital of Japan?', optionA: 'Osaka', optionB: 'Kyoto', optionC: 'Yokohama', optionD: 'Tokyo', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Which river runs through Paris?', optionA: 'Rhine', optionB: 'Thames', optionC: 'Seine', optionD: 'Danube', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the deepest point in the ocean?', optionA: 'Mariana Trench', optionB: 'Tonga Trench', optionC: 'Java Trench', optionD: 'Puerto Rico Trench', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Which country has the most islands?', optionA: 'Philippines', optionB: 'Indonesia', optionC: 'Sweden', optionD: 'Canada', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What is the capital of Canada?', optionA: 'Toronto', optionB: 'Vancouver', optionC: 'Ottawa', optionD: 'Montreal', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the driest continent?', optionA: 'Africa', optionB: 'Australia', optionC: 'Antarctica', optionD: 'South America', correctAnswer: 'optionC', timeLimit: 20 },
  ],
  'Sports': [
    { text: 'How many players are on a soccer team on the field?', optionA: '9', optionB: '10', optionC: '11', optionD: '12', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'In what sport is the term "love" used?', optionA: 'Golf', optionB: 'Tennis', optionC: 'Cricket', optionD: 'Badminton', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many rings are on the Olympic flag?', optionA: '3', optionB: '4', optionC: '5', optionD: '6', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What sport does Tiger Woods play?', optionA: 'Tennis', optionB: 'Baseball', optionC: 'Golf', optionD: 'Basketball', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'How long is a marathon in miles?', optionA: '24.2', optionB: '26.2', optionC: '28.2', optionD: '30.2', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What country hosted the first modern Olympics?', optionA: 'France', optionB: 'Italy', optionC: 'Greece', optionD: 'England', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'In basketball, how many points is a three-point shot worth?', optionA: '1', optionB: '2', optionC: '3', optionD: '4', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the national sport of Japan?', optionA: 'Karate', optionB: 'Judo', optionC: 'Sumo wrestling', optionD: 'Kendo', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'How many holes are played in a standard round of golf?', optionA: '9', optionB: '12', optionC: '15', optionD: '18', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What does "FIFA" stand for?', optionA: 'Football International Federation Association', optionB: 'Federation Internationale de Football Association', optionC: 'Football In France Association', optionD: 'First International Football Association', correctAnswer: 'optionB', timeLimit: 20 },
    { text: 'Which sport uses a shuttlecock?', optionA: 'Tennis', optionB: 'Badminton', optionC: 'Ping pong', optionD: 'Squash', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What team has won the most FIFA World Cups?', optionA: 'Germany', optionB: 'Italy', optionC: 'Argentina', optionD: 'Brazil', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'In American football, how many points is a touchdown?', optionA: '3', optionB: '5', optionC: '6', optionD: '7', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What sport is played at Wimbledon?', optionA: 'Cricket', optionB: 'Golf', optionC: 'Polo', optionD: 'Tennis', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'How many periods are in an ice hockey game?', optionA: '2', optionB: '3', optionC: '4', optionD: '5', correctAnswer: 'optionB', timeLimit: 15 },
  ],
  'Music': [
    { text: 'Who is known as the "King of Pop"?', optionA: 'Elvis Presley', optionB: 'Michael Jackson', optionC: 'Prince', optionD: 'Freddie Mercury', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'How many strings does a standard guitar have?', optionA: '4', optionB: '5', optionC: '6', optionD: '8', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What instrument has 88 keys?', optionA: 'Organ', optionB: 'Accordion', optionC: 'Piano', optionD: 'Harpsichord', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What band wrote "Bohemian Rhapsody"?', optionA: 'The Beatles', optionB: 'Led Zeppelin', optionC: 'Pink Floyd', optionD: 'Queen', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'Who composed the Four Seasons?', optionA: 'Mozart', optionB: 'Bach', optionC: 'Vivaldi', optionD: 'Beethoven', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the highest female singing voice?', optionA: 'Alto', optionB: 'Mezzo-soprano', optionC: 'Soprano', optionD: 'Contralto', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What city is known as the birthplace of jazz?', optionA: 'Chicago', optionB: 'New York', optionC: 'Memphis', optionD: 'New Orleans', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'Who sang "Like a Prayer"?', optionA: 'Whitney Houston', optionB: 'Madonna', optionC: 'Celine Dion', optionD: 'Janet Jackson', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many musicians are in a quartet?', optionA: '2', optionB: '3', optionC: '4', optionD: '5', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What does "forte" mean in music?', optionA: 'Slow', optionB: 'Loud', optionC: 'Soft', optionD: 'Fast', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who is known as the "Queen of Soul"?', optionA: 'Diana Ross', optionB: 'Tina Turner', optionC: 'Aretha Franklin', optionD: 'Whitney Houston', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What country is the band ABBA from?', optionA: 'Norway', optionB: 'Denmark', optionC: 'Finland', optionD: 'Sweden', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What is the lowest male singing voice?', optionA: 'Tenor', optionB: 'Baritone', optionC: 'Bass', optionD: 'Countertenor', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who wrote "Für Elise"?', optionA: 'Mozart', optionB: 'Chopin', optionC: 'Beethoven', optionD: 'Brahms', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What instrument does a drummer play?', optionA: 'Percussion', optionB: 'String', optionC: 'Brass', optionD: 'Woodwind', correctAnswer: 'optionA', timeLimit: 10 },
  ],
  'Movies & TV': [
    { text: 'What movie features a character named Forrest Gump?', optionA: 'The Green Mile', optionB: 'Cast Away', optionC: 'Forrest Gump', optionD: 'Big', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who directed "Jurassic Park"?', optionA: 'James Cameron', optionB: 'Steven Spielberg', optionC: 'George Lucas', optionD: 'Ridley Scott', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the highest-grossing film of all time?', optionA: 'Avengers: Endgame', optionB: 'Titanic', optionC: 'Avatar', optionD: 'Star Wars', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who plays Iron Man in the MCU?', optionA: 'Chris Evans', optionB: 'Robert Downey Jr.', optionC: 'Chris Hemsworth', optionD: 'Mark Ruffalo', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the name of the wizarding school in Harry Potter?', optionA: 'Beauxbatons', optionB: 'Durmstrang', optionC: 'Hogwarts', optionD: 'Ilvermorny', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What TV show features a character named Walter White?', optionA: 'The Wire', optionB: 'Better Call Saul', optionC: 'Breaking Bad', optionD: 'Ozark', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who voiced Elsa in Frozen?', optionA: 'Kristen Bell', optionB: 'Idina Menzel', optionC: 'Demi Lovato', optionD: 'Mandy Moore', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What year was the first Star Wars movie released?', optionA: '1975', optionB: '1976', optionC: '1977', optionD: '1978', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the name of Batman\'s butler?', optionA: 'James', optionB: 'Alfred', optionC: 'Bernard', optionD: 'Winston', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Which TV show is set in the fictional town of Springfield?', optionA: 'Family Guy', optionB: 'South Park', optionC: 'The Simpsons', optionD: 'King of the Hill', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who directed "Inception"?', optionA: 'Steven Spielberg', optionB: 'Christopher Nolan', optionC: 'James Cameron', optionD: 'Denis Villeneuve', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the name of the shark in Finding Nemo?', optionA: 'Bruce', optionB: 'Chum', optionC: 'Anchor', optionD: 'Marlin', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What Netflix show is set in Hawkins, Indiana?', optionA: 'The OA', optionB: 'Dark', optionC: 'Stranger Things', optionD: 'Black Mirror', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who played Jack in Titanic?', optionA: 'Brad Pitt', optionB: 'Leonardo DiCaprio', optionC: 'Matt Damon', optionD: 'Tom Cruise', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What Disney movie features a character named Simba?', optionA: 'Bambi', optionB: 'The Jungle Book', optionC: 'Madagascar', optionD: 'The Lion King', correctAnswer: 'optionD', timeLimit: 10 },
  ],
  'Literature': [
    { text: 'Who wrote "Romeo and Juliet"?', optionA: 'Charles Dickens', optionB: 'Jane Austen', optionC: 'William Shakespeare', optionD: 'Mark Twain', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the name of the wizard in "The Lord of the Rings"?', optionA: 'Dumbledore', optionB: 'Merlin', optionC: 'Gandalf', optionD: 'Oz', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who wrote "1984"?', optionA: 'Aldous Huxley', optionB: 'Ray Bradbury', optionC: 'George Orwell', optionD: 'H.G. Wells', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What novel begins with "Call me Ishmael"?', optionA: 'Moby Dick', optionB: 'Treasure Island', optionC: 'Robinson Crusoe', optionD: 'The Old Man and the Sea', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who wrote "Pride and Prejudice"?', optionA: 'Emily Brontë', optionB: 'Jane Austen', optionC: 'Virginia Woolf', optionD: 'Mary Shelley', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the name of Sherlock Holmes\' sidekick?', optionA: 'Watson', optionB: 'Wilson', optionC: 'Williams', optionD: 'Wallace', correctAnswer: 'optionA', timeLimit: 10 },
    { text: 'Who wrote "The Great Gatsby"?', optionA: 'Ernest Hemingway', optionB: 'F. Scott Fitzgerald', optionC: 'John Steinbeck', optionD: 'William Faulkner', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What genre is "Dracula" by Bram Stoker?', optionA: 'Science fiction', optionB: 'Fantasy', optionC: 'Horror', optionD: 'Romance', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who wrote "To Kill a Mockingbird"?', optionA: 'Harper Lee', optionB: 'Truman Capote', optionC: 'Toni Morrison', optionD: 'Maya Angelou', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What Shakespeare play features the character Hamlet?', optionA: 'Macbeth', optionB: 'Othello', optionC: 'King Lear', optionD: 'Hamlet', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Who wrote "The Hobbit"?', optionA: 'C.S. Lewis', optionB: 'J.R.R. Tolkien', optionC: 'George R.R. Martin', optionD: 'Terry Pratchett', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the first book of the Harry Potter series?', optionA: 'Chamber of Secrets', optionB: 'Prisoner of Azkaban', optionC: 'Philosopher\'s Stone', optionD: 'Goblet of Fire', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who wrote "The Catcher in the Rye"?', optionA: 'Jack Kerouac', optionB: 'J.D. Salinger', optionC: 'John Updike', optionD: 'Norman Mailer', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What fairy tale features a glass slipper?', optionA: 'Sleeping Beauty', optionB: 'Snow White', optionC: 'Cinderella', optionD: 'Rapunzel', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who wrote "The Divine Comedy"?', optionA: 'Homer', optionB: 'Virgil', optionC: 'Dante Alighieri', optionD: 'Ovid', correctAnswer: 'optionC', timeLimit: 15 },
  ],
  'Technology': [
    { text: 'What does "HTML" stand for?', optionA: 'Hyper Text Markup Language', optionB: 'High Tech Modern Language', optionC: 'Hyper Transfer Markup Language', optionD: 'Home Tool Markup Language', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who is the co-founder of Apple Inc.?', optionA: 'Bill Gates', optionB: 'Steve Jobs', optionC: 'Jeff Bezos', optionD: 'Elon Musk', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What does "CPU" stand for?', optionA: 'Central Processing Unit', optionB: 'Computer Personal Unit', optionC: 'Central Program Utility', optionD: 'Core Processing Unit', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What programming language is known for its snake mascot?', optionA: 'Java', optionB: 'Ruby', optionC: 'Python', optionD: 'Go', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What year was the iPhone first released?', optionA: '2005', optionB: '2006', optionC: '2007', optionD: '2008', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What does "URL" stand for?', optionA: 'Universal Resource Locator', optionB: 'Uniform Resource Locator', optionC: 'Unified Resource Link', optionD: 'Universal Reference Link', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who founded Microsoft?', optionA: 'Steve Jobs', optionB: 'Mark Zuckerberg', optionC: 'Larry Page', optionD: 'Bill Gates', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What does "RAM" stand for?', optionA: 'Random Access Memory', optionB: 'Read Access Memory', optionC: 'Rapid Access Module', optionD: 'Random Applied Memory', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What social media platform is known for 280-character posts?', optionA: 'Facebook', optionB: 'Instagram', optionC: 'X (Twitter)', optionD: 'LinkedIn', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What does "AI" stand for?', optionA: 'Automated Intelligence', optionB: 'Artificial Intelligence', optionC: 'Applied Intelligence', optionD: 'Advanced Integration', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What company created the Android operating system?', optionA: 'Apple', optionB: 'Microsoft', optionC: 'Google', optionD: 'Samsung', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What does "HTTP" stand for?', optionA: 'HyperText Transfer Protocol', optionB: 'High Tech Transfer Protocol', optionC: 'Hyper Transfer Text Protocol', optionD: 'Home Text Transfer Protocol', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who is the CEO of Tesla?', optionA: 'Jeff Bezos', optionB: 'Tim Cook', optionC: 'Elon Musk', optionD: 'Sundar Pichai', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What does "Wi-Fi" stand for?', optionA: 'Wireless Fidelity', optionB: 'Wireless Frequency', optionC: 'Wide Fidelity', optionD: 'It doesn\'t stand for anything', correctAnswer: 'optionD', timeLimit: 20 },
    { text: 'What was the first widely-used web browser?', optionA: 'Internet Explorer', optionB: 'Firefox', optionC: 'Mosaic', optionD: 'Safari', correctAnswer: 'optionC', timeLimit: 20 },
  ],
  'Mathematics': [
    { text: 'What is the value of Pi (π) to two decimal places?', optionA: '3.12', optionB: '3.14', optionC: '3.16', optionD: '3.18', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the square root of 144?', optionA: '10', optionB: '11', optionC: '12', optionD: '13', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is 7 multiplied by 8?', optionA: '54', optionB: '56', optionC: '58', optionD: '62', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is a polygon with 8 sides called?', optionA: 'Hexagon', optionB: 'Heptagon', optionC: 'Octagon', optionD: 'Decagon', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is 15% of 200?', optionA: '25', optionB: '30', optionC: '35', optionD: '40', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the next prime number after 7?', optionA: '8', optionB: '9', optionC: '10', optionD: '11', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'How many degrees are in a right angle?', optionA: '45', optionB: '60', optionC: '90', optionD: '120', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is 2 to the power of 10?', optionA: '512', optionB: '1024', optionC: '2048', optionD: '4096', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the sum of angles in a triangle?', optionA: '90°', optionB: '180°', optionC: '270°', optionD: '360°', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the factorial of 5 (5!)?', optionA: '60', optionB: '100', optionC: '120', optionD: '150', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the greatest common divisor of 12 and 18?', optionA: '4', optionB: '6', optionC: '8', optionD: '12', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What type of number is the square root of 2?', optionA: 'Rational', optionB: 'Irrational', optionC: 'Integer', optionD: 'Whole', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the area of a circle formula?', optionA: '2πr', optionB: 'πr²', optionC: 'πd', optionD: '2πr²', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is 999 + 1?', optionA: '1000', optionB: '1001', optionC: '9999', optionD: '10000', correctAnswer: 'optionA', timeLimit: 10 },
    { text: 'What is the Roman numeral for 50?', optionA: 'L', optionB: 'C', optionC: 'D', optionD: 'X', correctAnswer: 'optionA', timeLimit: 15 },
  ],
  'Animals': [
    { text: 'What is the fastest land animal?', optionA: 'Lion', optionB: 'Cheetah', optionC: 'Horse', optionD: 'Gazelle', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the largest animal on Earth?', optionA: 'Elephant', optionB: 'Giraffe', optionC: 'Blue whale', optionD: 'Hippopotamus', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'How many legs does a spider have?', optionA: '6', optionB: '8', optionC: '10', optionD: '12', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is a group of lions called?', optionA: 'Pack', optionB: 'Flock', optionC: 'Herd', optionD: 'Pride', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What is the only mammal that can fly?', optionA: 'Flying squirrel', optionB: 'Bat', optionC: 'Sugar glider', optionD: 'Colugo', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many hearts does an octopus have?', optionA: '1', optionB: '2', optionC: '3', optionD: '4', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What animal is known as the "King of the Jungle"?', optionA: 'Tiger', optionB: 'Lion', optionC: 'Elephant', optionD: 'Gorilla', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the slowest animal in the world?', optionA: 'Turtle', optionB: 'Snail', optionC: 'Sloth', optionD: 'Koala', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What animal has the longest lifespan?', optionA: 'Elephant', optionB: 'Tortoise', optionC: 'Whale', optionD: 'Parrot', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is a baby kangaroo called?', optionA: 'Pup', optionB: 'Cub', optionC: 'Joey', optionD: 'Kit', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'How long can a dolphin hold its breath?', optionA: '2 minutes', optionB: '5 minutes', optionC: '8-10 minutes', optionD: '20 minutes', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What is the tallest animal in the world?', optionA: 'Elephant', optionB: 'Giraffe', optionC: 'Ostrich', optionD: 'Moose', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What animal sleeps up to 22 hours a day?', optionA: 'Sloth', optionB: 'Koala', optionC: 'Cat', optionD: 'Bat', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is a group of wolves called?', optionA: 'Pack', optionB: 'Herd', optionC: 'Flock', optionD: 'Colony', correctAnswer: 'optionA', timeLimit: 10 },
    { text: 'What animal has the strongest bite force?', optionA: 'Lion', optionB: 'Great white shark', optionC: 'Crocodile', optionD: 'Hippopotamus', correctAnswer: 'optionC', timeLimit: 20 },
  ],
  'Food & Cooking': [
    { text: 'What country is sushi from?', optionA: 'China', optionB: 'Korea', optionC: 'Japan', optionD: 'Thailand', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the main ingredient in guacamole?', optionA: 'Tomato', optionB: 'Avocado', optionC: 'Lime', optionD: 'Onion', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What pasta is shaped like little ears?', optionA: 'Penne', optionB: 'Fusilli', optionC: 'Orecchiette', optionD: 'Farfalle', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What spice is known as the world\'s most expensive by weight?', optionA: 'Vanilla', optionB: 'Cardamom', optionC: 'Saffron', optionD: 'Cinnamon', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the national dish of Spain?', optionA: 'Tapas', optionB: 'Paella', optionC: 'Gazpacho', optionD: 'Tortilla', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What fruit is known as the "king of fruits"?', optionA: 'Mango', optionB: 'Pineapple', optionC: 'Durian', optionD: 'Jackfruit', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What country is the origin of pizza?', optionA: 'France', optionB: 'Greece', optionC: 'Italy', optionD: 'Spain', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the main ingredient in hummus?', optionA: 'Lentils', optionB: 'Chickpeas', optionC: 'Black beans', optionD: 'Peas', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What does "al dente" mean in cooking?', optionA: 'To the tooth', optionB: 'To the bite', optionC: 'Firm', optionD: 'Soft', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What grain is used to make traditional Japanese sake?', optionA: 'Wheat', optionB: 'Barley', optionC: 'Rice', optionD: 'Millet', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What herb is traditionally used in pesto?', optionA: 'Parsley', optionB: 'Cilantro', optionC: 'Basil', optionD: 'Oregano', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the most consumed beverage in the world after water?', optionA: 'Coffee', optionB: 'Tea', optionC: 'Milk', optionD: 'Beer', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What cheese is traditionally used on a Margherita pizza?', optionA: 'Cheddar', optionB: 'Parmesan', optionC: 'Mozzarella', optionD: 'Gouda', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the smallest country that produces coffee?', optionA: 'Jamaica', optionB: 'Rwanda', optionC: 'Yemen', optionD: 'El Salvador', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What vegetable is known as the "alligator pear"?', optionA: 'Zucchini', optionB: 'Cucumber', optionC: 'Avocado', optionD: 'Eggplant', correctAnswer: 'optionC', timeLimit: 15 },
  ],
  'Art & Culture': [
    { text: 'Who painted the Mona Lisa?', optionA: 'Michelangelo', optionB: 'Raphael', optionC: 'Leonardo da Vinci', optionD: 'Botticelli', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What art movement is Salvador Dalí associated with?', optionA: 'Impressionism', optionB: 'Cubism', optionC: 'Surrealism', optionD: 'Pop Art', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What museum houses the Mona Lisa?', optionA: 'British Museum', optionB: 'The Louvre', optionC: 'Uffizi Gallery', optionD: 'Prado Museum', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who painted "Starry Night"?', optionA: 'Claude Monet', optionB: 'Pablo Picasso', optionC: 'Vincent van Gogh', optionD: 'Edvard Munch', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the Japanese art of paper folding called?', optionA: 'Ikebana', optionB: 'Origami', optionC: 'Bonsai', optionD: 'Kintsugi', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What art movement featured artists like Monet and Renoir?', optionA: 'Realism', optionB: 'Expressionism', optionC: 'Impressionism', optionD: 'Dadaism', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who created the sculpture "David"?', optionA: 'Donatello', optionB: 'Bernini', optionC: 'Rodin', optionD: 'Michelangelo', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What is the study of ancient cultures through artifacts called?', optionA: 'Anthropology', optionB: 'Archaeology', optionC: 'Sociology', optionD: 'History', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who is known for the pop art painting of Campbell\'s Soup cans?', optionA: 'Roy Lichtenstein', optionB: 'Andy Warhol', optionC: 'Keith Haring', optionD: 'Jasper Johns', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is "The Thinker" made of?', optionA: 'Marble', optionB: 'Bronze', optionC: 'Stone', optionD: 'Clay', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the largest art museum in the world?', optionA: 'The Louvre', optionB: 'British Museum', optionC: 'Metropolitan Museum', optionD: 'Hermitage Museum', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who painted "The Scream"?', optionA: 'Edvard Munch', optionB: 'Vincent van Gogh', optionC: 'Pablo Picasso', optionD: 'Francis Bacon', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What country is origami from?', optionA: 'China', optionB: 'Korea', optionC: 'Japan', optionD: 'Thailand', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is traditional Japanese ink painting called?', optionA: 'Sumi-e', optionB: 'Ukiyo-e', optionC: 'Shodo', optionD: 'Kintsugi', correctAnswer: 'optionA', timeLimit: 20 },
    { text: 'What is the color scheme using only one color with variations?', optionA: 'Complementary', optionB: 'Analogous', optionC: 'Monochromatic', optionD: 'Triadic', correctAnswer: 'optionC', timeLimit: 15 },
  ],
  'Nature & Environment': [
    { text: 'What is the process by which plants make food using sunlight?', optionA: 'Respiration', optionB: 'Photosynthesis', optionC: 'Fermentation', optionD: 'Decomposition', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the largest rainforest in the world?', optionA: 'Congo', optionB: 'Daintree', optionC: 'Amazon', optionD: 'Tongass', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What gas makes up most of Earth\'s atmosphere?', optionA: 'Oxygen', optionB: 'Carbon dioxide', optionC: 'Nitrogen', optionD: 'Argon', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the process of water turning into vapor called?', optionA: 'Condensation', optionB: 'Evaporation', optionC: 'Precipitation', optionD: 'Sublimation', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What layer of the Earth\'s atmosphere contains the ozone layer?', optionA: 'Troposphere', optionB: 'Mesosphere', optionC: 'Stratosphere', optionD: 'Thermosphere', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What type of energy comes from the sun?', optionA: 'Kinetic', optionB: 'Thermal', optionC: 'Solar', optionD: 'Nuclear', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the term for a period of extremely low rainfall?', optionA: 'Famine', optionB: 'Drought', optionC: 'Monsoon', optionD: 'El Niño', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the most common type of renewable energy?', optionA: 'Nuclear', optionB: 'Solar', optionC: 'Wind', optionD: 'Hydropower', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'How much of Earth\'s surface is covered by water?', optionA: '51%', optionB: '61%', optionC: '71%', optionD: '81%', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the term for species at risk of extinction?', optionA: 'Vulnerable', optionB: 'Endangered', optionC: 'Threatened', optionD: 'Extinct', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the process of turning waste into reusable material?', optionA: 'Composting', optionB: 'Recycling', optionC: 'Incineration', optionD: 'Landfill', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the name for a community of living organisms and their environment?', optionA: 'Biome', optionB: 'Ecosystem', optionC: 'Habitat', optionD: 'Biosphere', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What natural disaster is measured by the Richter scale?', optionA: 'Tornado', optionB: 'Hurricane', optionC: 'Earthquake', optionD: 'Tsunami', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the hottest layer of the Earth?', optionA: 'Crust', optionB: 'Mantle', optionC: 'Outer core', optionD: 'Inner core', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What causes tides in the ocean?', optionA: 'Wind', optionB: 'Earth\'s rotation', optionC: 'The Moon\'s gravity', optionD: 'Underwater volcanoes', correctAnswer: 'optionC', timeLimit: 15 },
  ],
  'Space & Astronomy': [
    { text: 'What is the closest planet to the Sun?', optionA: 'Venus', optionB: 'Earth', optionC: 'Mercury', optionD: 'Mars', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the largest planet in our solar system?', optionA: 'Saturn', optionB: 'Neptune', optionC: 'Uranus', optionD: 'Jupiter', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'How many planets are in our solar system?', optionA: '7', optionB: '8', optionC: '9', optionD: '10', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What galaxy do we live in?', optionA: 'Andromeda', optionB: 'Milky Way', optionC: 'Triangulum', optionD: 'Centaurus A', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who was the first person to walk on the Moon?', optionA: 'Buzz Aldrin', optionB: 'Yuri Gagarin', optionC: 'Neil Armstrong', optionD: 'John Glenn', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is a light-year a measure of?', optionA: 'Time', optionB: 'Speed', optionC: 'Distance', optionD: 'Brightness', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What planet is known for its prominent rings?', optionA: 'Jupiter', optionB: 'Uranus', optionC: 'Neptune', optionD: 'Saturn', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the Sun primarily made of?', optionA: 'Helium', optionB: 'Hydrogen', optionC: 'Oxygen', optionD: 'Carbon', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is a comet\'s tail made of?', optionA: 'Fire', optionB: 'Gas and dust', optionC: 'Water', optionD: 'Rocks', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How long does it take sunlight to reach Earth?', optionA: '4 minutes', optionB: '6 minutes', optionC: '8 minutes', optionD: '12 minutes', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the smallest planet in our solar system?', optionA: 'Mars', optionB: 'Mercury', optionC: 'Venus', optionD: 'Pluto', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What causes a solar eclipse?', optionA: 'Earth between Sun and Moon', optionB: 'Moon between Sun and Earth', optionC: 'Sun between Moon and Earth', optionD: 'Planets aligning', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the International Space Station?', optionA: 'A satellite', optionB: 'A space telescope', optionC: 'An orbiting laboratory', optionD: 'A space hotel', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the name of the largest volcano in the solar system?', optionA: 'Mount Everest', optionB: 'Olympus Mons', optionC: 'Mauna Kea', optionD: 'Tharsis Montes', correctAnswer: 'optionB', timeLimit: 20 },
    { text: 'What force keeps the Moon in orbit around Earth?', optionA: 'Magnetism', optionB: 'Inertia', optionC: 'Gravity', optionD: 'Air resistance', correctAnswer: 'optionC', timeLimit: 10 },
  ],
  'Mythology': [
    { text: 'Who is the Greek god of thunder?', optionA: 'Poseidon', optionB: 'Zeus', optionC: 'Ares', optionD: 'Apollo', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the Roman name for the Greek goddess Athena?', optionA: 'Diana', optionB: 'Venus', optionC: 'Minerva', optionD: 'Juno', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who is the Norse god of war?', optionA: 'Thor', optionB: 'Loki', optionC: 'Odin', optionD: 'Tyr', correctAnswer: 'optionD', timeLimit: 20 },
    { text: 'What creature is half man, half horse in Greek mythology?', optionA: 'Minotaur', optionB: 'Centaur', optionC: 'Satyr', optionD: 'Siren', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who is the Egyptian god of the dead?', optionA: 'Ra', optionB: 'Horus', optionC: 'Anubis', optionD: 'Osiris', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What was the name of the winged horse in Greek mythology?', optionA: 'Pegasus', optionB: 'Sleipnir', optionC: 'Hippogriff', optionD: 'Peryton', correctAnswer: 'optionA', timeLimit: 10 },
    { text: 'Who killed Achilles?', optionA: 'Hector', optionB: 'Paris', optionC: 'Agamemnon', optionD: 'Odysseus', correctAnswer: 'optionB', timeLimit: 20 },
    { text: 'What is the name of Thor\'s hammer?', optionA: 'Gungnir', optionB: 'Mjolnir', optionC: 'Excalibur', optionD: 'Draupnir', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who opened Pandora\'s box?', optionA: 'Pandora', optionB: 'Prometheus', optionC: 'Epimetheus', optionD: 'Hermes', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What creature had the head of a bull and body of a man?', optionA: 'Cyclops', optionB: 'Centaur', optionC: 'Minotaur', optionD: 'Satyr', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who is the Greek goddess of love?', optionA: 'Hera', optionB: 'Artemis', optionC: 'Aphrodite', optionD: 'Demeter', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What river flows through the underworld in Greek mythology?', optionA: 'Styx', optionB: 'Lethe', optionC: 'Acheron', optionD: 'Phlegethon', correctAnswer: 'optionA', timeLimit: 20 },
    { text: 'Who is the king of the Norse gods?', optionA: 'Thor', optionB: 'Freya', optionC: 'Loki', optionD: 'Odin', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What was Medusa\'s hair made of?', optionA: 'Fire', optionB: 'Snakes', optionC: 'Spiders', optionD: 'Thorns', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who crafted the labymth for the Minotaur?', optionA: 'Hephaestus', optionB: 'Daedalus', optionC: 'Icarus', optionD: 'Orpheus', correctAnswer: 'optionB', timeLimit: 20 },
  ],
  'Languages': [
    { text: 'What is the most spoken language in the world?', optionA: 'English', optionB: 'Spanish', optionC: 'Mandarin Chinese', optionD: 'Hindi', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What language has the most native speakers in Europe?', optionA: 'French', optionB: 'English', optionC: 'Spanish', optionD: 'German', correctAnswer: 'optionD', timeLimit: 20 },
    { text: 'What does "hola" mean in Spanish?', optionA: 'Goodbye', optionB: 'Hello', optionC: 'Please', optionD: 'Thank you', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What language is spoken in Brazil?', optionA: 'Spanish', optionB: 'Portuguese', optionC: 'French', optionD: 'English', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'How many official languages does the UN have?', optionA: '4', optionB: '5', optionC: '6', optionD: '8', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is "merci" in French?', optionA: 'Hello', optionB: 'Goodbye', optionC: 'Please', optionD: 'Thank you', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What alphabet does Russian use?', optionA: 'Latin', optionB: 'Greek', optionC: 'Cyrillic', optionD: 'Arabic', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the oldest written language still in use?', optionA: 'Latin', optionB: 'Greek', optionC: 'Hebrew', optionD: 'Chinese', correctAnswer: 'optionD', timeLimit: 20 },
    { text: 'What does "ciao" mean in Italian?', optionA: 'Hello and goodbye', optionB: 'Good morning', optionC: 'Thank you', optionD: 'Excuse me', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What language has the most words?', optionA: 'Spanish', optionB: 'French', optionC: 'English', optionD: 'German', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What country speaks the most Arabic?', optionA: 'Iraq', optionB: 'Saudi Arabia', optionC: 'Egypt', optionD: 'Algeria', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What does "namaste" mean in Hindi?', optionA: 'Goodbye', optionB: 'I bow to you', optionC: 'Thank you', optionD: 'Welcome', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the official language of Mexico?', optionA: 'Portuguese', optionB: 'English', optionC: 'Spanish', optionD: 'French', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'How many languages are there in the world approximately?', optionA: '3,000', optionB: '5,000', optionC: '7,000', optionD: '10,000', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What writing system does Japanese use?', optionA: 'One alphabet', optionB: 'Two syllabaries + kanji', optionC: 'Only kanji', optionD: 'Latin script', correctAnswer: 'optionB', timeLimit: 20 },
  ],
  'Health & Medicine': [
    { text: 'What is the largest organ in the human body?', optionA: 'Liver', optionB: 'Heart', optionC: 'Skin', optionD: 'Brain', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'How many bones does an adult human have?', optionA: '186', optionB: '206', optionC: '226', optionD: '256', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What vitamin does sunlight help your body produce?', optionA: 'Vitamin A', optionB: 'Vitamin B', optionC: 'Vitamin C', optionD: 'Vitamin D', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the normal resting heart rate for adults?', optionA: '40-50 bpm', optionB: '60-100 bpm', optionC: '100-120 bpm', optionD: '120-140 bpm', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What blood type is known as the universal donor?', optionA: 'A+', optionB: 'B-', optionC: 'AB+', optionD: 'O-', correctAnswer: 'optionD', timeLimit: 15 },
    { text: 'What is the longest bone in the human body?', optionA: 'Humerus', optionB: 'Tibia', optionC: 'Femur', optionD: 'Fibula', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'How much of the human body is water?', optionA: '40%', optionB: '50%', optionC: '60%', optionD: '70%', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the main function of red blood cells?', optionA: 'Fight infection', optionB: 'Carry oxygen', optionC: 'Clot blood', optionD: 'Produce antibodies', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the medical term for high blood pressure?', optionA: 'Hypotension', optionB: 'Hypertension', optionC: 'Hyperglycemia', optionD: 'Hypoglycemia', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many chromosomes do humans have?', optionA: '23', optionB: '44', optionC: '46', optionD: '48', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What part of the brain controls balance?', optionA: 'Cerebrum', optionB: 'Cerebellum', optionC: 'Brain stem', optionD: 'Frontal lobe', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What mineral is essential for strong bones?', optionA: 'Iron', optionB: 'Zinc', optionC: 'Calcium', optionD: 'Potassium', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'How many times does the average heart beat per day?', optionA: '50,000', optionB: '80,000', optionC: '100,000', optionD: '150,000', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What is the smallest bone in the human body?', optionA: 'Stapes', optionB: 'Incus', optionC: 'Malleus', optionD: 'Phalange', correctAnswer: 'optionA', timeLimit: 20 },
    { text: 'What is the recommended hours of sleep for adults?', optionA: '4-5 hours', optionB: '5-6 hours', optionC: '7-9 hours', optionD: '10-12 hours', correctAnswer: 'optionC', timeLimit: 10 },
  ],
  'Famous People': [
    { text: 'Who invented the telephone?', optionA: 'Thomas Edison', optionB: 'Alexander Graham Bell', optionC: 'Nikola Tesla', optionD: 'Guglielmo Marconi', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who was the first woman to win a Nobel Prize?', optionA: 'Rosalind Franklin', optionB: 'Marie Curie', optionC: 'Dorothy Hodgkin', optionD: 'Ada Lovelace', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who wrote the theory of relativity?', optionA: 'Isaac Newton', optionB: 'Stephen Hawking', optionC: 'Nikola Tesla', optionD: 'Albert Einstein', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Who was the first person to circumnavigate the globe?', optionA: 'Christopher Columbus', optionB: 'Vasco da Gama', optionC: 'Ferdinand Magellan', optionD: 'James Cook', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who painted the ceiling of the Sistine Chapel?', optionA: 'Leonardo da Vinci', optionB: 'Raphael', optionC: 'Michelangelo', optionD: 'Caravaggio', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who discovered penicillin?', optionA: 'Louis Pasteur', optionB: 'Alexander Fleming', optionC: 'Joseph Lister', optionD: 'Robert Koch', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who was the civil rights leader known for "I Have a Dream"?', optionA: 'Malcolm X', optionB: 'Martin Luther King Jr.', optionC: 'Rosa Parks', optionD: 'Nelson Mandela', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who developed the polio vaccine?', optionA: 'Jonas Salk', optionB: 'Albert Sabin', optionC: 'Louis Pasteur', optionD: 'Edward Jenner', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'Who was the first female Prime Minister of the UK?', optionA: 'Theresa May', optionB: 'Indira Gandhi', optionC: 'Margaret Thatcher', optionD: 'Golda Meir', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who founded Amazon?', optionA: 'Bill Gates', optionB: 'Elon Musk', optionC: 'Jeff Bezos', optionD: 'Mark Zuckerberg', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who invented the light bulb?', optionA: 'Nikola Tesla', optionB: 'Thomas Edison', optionC: 'Benjamin Franklin', optionD: 'Michael Faraday', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who was known as the "Father of Computers"?', optionA: 'Alan Turing', optionB: 'Charles Babbage', optionC: 'John von Neumann', optionD: 'Ada Lovelace', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who was the first African-American President of the USA?', optionA: 'Colin Powell', optionB: 'Barack Obama', optionC: 'Jesse Jackson', optionD: 'Kamala Harris', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who wrote the "I Have a Dream" speech?', optionA: 'John F. Kennedy', optionB: 'Maya Angelou', optionC: 'Martin Luther King Jr.', optionD: 'James Baldwin', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'Who discovered radioactivity?', optionA: 'Marie Curie', optionB: 'Henri Becquerel', optionC: 'Ernest Rutherford', optionD: 'Niels Bohr', correctAnswer: 'optionB', timeLimit: 20 },
  ],
  'Video Games': [
    { text: 'What video game franchise features Mario?', optionA: 'The Legend of Zelda', optionB: 'Super Mario', optionC: 'Sonic', optionD: 'Donkey Kong', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What year was the original PlayStation released?', optionA: '1992', optionB: '1994', optionC: '1996', optionD: '1998', correctAnswer: 'optionB', timeLimit: 20 },
    { text: 'What is the best-selling video game of all time?', optionA: 'Tetris', optionB: 'Minecraft', optionC: 'GTA V', optionD: 'Wii Sports', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Who is the main character in The Legend of Zelda?', optionA: 'Zelda', optionB: 'Link', optionC: 'Ganon', optionD: 'Navi', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What company created Pokémon?', optionA: 'Sony', optionB: 'Sega', optionC: 'Nintendo', optionD: 'Bandai', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What game is known for the phrase "The cake is a lie"?', optionA: 'Half-Life', optionB: 'Portal', optionC: 'BioShock', optionD: 'Mass Effect', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the name of Sonic\'s sidekick?', optionA: 'Shadow', optionB: 'Knuckles', optionC: 'Tails', optionD: 'Amy', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What game features a battle royale with 100 players?', optionA: 'Minecraft', optionB: 'Roblox', optionC: 'Fortnite', optionD: 'Among Us', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What company developed the Xbox?', optionA: 'Sony', optionB: 'Nintendo', optionC: 'Microsoft', optionD: 'Sega', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What game features block-building in a sandbox world?', optionA: 'Terraria', optionB: 'Roblox', optionC: 'Fortnite', optionD: 'Minecraft', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the name of the princess Mario rescues?', optionA: 'Daisy', optionB: 'Rosalina', optionC: 'Peach', optionD: 'Pauline', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What genre is Street Fighter?', optionA: 'RPG', optionB: 'Fighting', optionC: 'Platformer', optionD: 'Shooter', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What game features a character named Master Chief?', optionA: 'Destiny', optionB: 'Halo', optionC: 'Call of Duty', optionD: 'Titanfall', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the highest-selling gaming console of all time?', optionA: 'Xbox 360', optionB: 'Wii', optionC: 'Nintendo DS', optionD: 'PS2', correctAnswer: 'optionD', timeLimit: 20 },
    { text: 'What game features impostors and crewmates?', optionA: 'Fall Guys', optionB: 'Overcooked', optionC: 'Among Us', optionD: 'Gartic Phone', correctAnswer: 'optionC', timeLimit: 10 },
  ],
  'World Records': [
    { text: 'What is the tallest building in the world?', optionA: 'Shanghai Tower', optionB: 'Burj Khalifa', optionC: 'Abraj Al-Bait', optionD: 'Ping An Finance Centre', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the fastest land speed record?', optionA: '763 mph', optionB: '1,000 mph', optionC: '500 mph', optionD: '600 mph', correctAnswer: 'optionA', timeLimit: 20 },
    { text: 'Who holds the record for most Olympic gold medals?', optionA: 'Usain Bolt', optionB: 'Carl Lewis', optionC: 'Michael Phelps', optionD: 'Larisa Latynina', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the longest river in the world?', optionA: 'Amazon', optionB: 'Nile', optionC: 'Yangtze', optionD: 'Mississippi', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What country has won the most FIFA World Cups?', optionA: 'Germany', optionB: 'Italy', optionC: 'Argentina', optionD: 'Brazil', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the deepest point in the ocean?', optionA: 'Tonga Trench', optionB: 'Java Trench', optionC: 'Mariana Trench', optionD: 'Puerto Rico Trench', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'Who holds the record for fastest 100m sprint?', optionA: 'Tyson Gay', optionB: 'Yohan Blake', optionC: 'Justin Gatlin', optionD: 'Usain Bolt', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What is the largest country by area?', optionA: 'Canada', optionB: 'China', optionC: 'USA', optionD: 'Russia', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Who has scored the most international football goals?', optionA: 'Pelé', optionB: 'Lionel Messi', optionC: 'Cristiano Ronaldo', optionD: 'Ali Daei', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the heaviest animal ever recorded?', optionA: 'African elephant', optionB: 'Blue whale', optionC: 'Colossal squid', optionD: 'Whale shark', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the most visited country in the world?', optionA: 'USA', optionB: 'Spain', optionC: 'France', optionD: 'Italy', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the longest wall ever built?', optionA: 'Hadrian\'s Wall', optionB: 'Berlin Wall', optionC: 'Western Wall', optionD: 'Great Wall of China', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Who has won the most Grand Slam tennis titles (men)?', optionA: 'Roger Federer', optionB: 'Rafael Nadal', optionC: 'Novak Djokovic', optionD: 'Pete Sampras', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the highest mountain in the world?', optionA: 'K2', optionB: 'Kangchenjunga', optionC: 'Mount Everest', optionD: 'Lhotse', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the most expensive painting ever sold?', optionA: 'The Mona Lisa', optionB: 'Salvator Mundi', optionC: 'The Starry Night', optionD: 'Interchange', correctAnswer: 'optionB', timeLimit: 20 },
  ],
  'Music Theory': [
    { text: 'How many notes are in a chromatic scale?', optionA: '7', optionB: '10', optionC: '12', optionD: '14', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What does "piano" mean as a dynamic marking?', optionA: 'Loud', optionB: 'Soft', optionC: 'Fast', optionD: 'Slow', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the interval between two notes of the same name called?', optionA: 'Fifth', optionB: 'Third', optionC: 'Octave', optionD: 'Unison', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What time signature is common in a waltz?', optionA: '2/4', optionB: '3/4', optionC: '4/4', optionD: '6/8', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What clef is also known as the G clef?', optionA: 'Bass clef', optionB: 'Treble clef', optionC: 'Alto clef', optionD: 'Tenor clef', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is a group of three notes played in the time of two called?', optionA: 'Trill', optionB: 'Triplet', optionC: 'Tremolo', optionD: 'Glissando', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What key has no sharps or flats?', optionA: 'C major', optionB: 'G major', optionC: 'F major', optionD: 'D major', correctAnswer: 'optionA', timeLimit: 10 },
    { text: 'What does "allegro" mean?', optionA: 'Slowly', optionB: 'Fast and lively', optionC: 'Very loud', optionD: 'Very soft', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'How many strings does a standard violin have?', optionA: '2', optionB: '3', optionC: '4', optionD: '6', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is a chord with three notes called?', optionA: 'Dyad', optionB: 'Triad', optionC: 'Tetrad', optionD: 'Pentad', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What does "fortissimo" mean?', optionA: 'Very soft', optionB: 'Very loud', optionC: 'Moderately', optionD: 'Gradually softer', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the pattern of whole and half steps in a major scale?', optionA: 'W-H-W-W-H-W-W', optionB: 'W-W-H-W-W-W-H', optionC: 'W-H-W-W-H-W-H', optionD: 'H-W-W-H-W-W-W', correctAnswer: 'optionB', timeLimit: 20 },
    { text: 'What does "da capo" mean?', optionA: 'From the beginning', optionB: 'From the sign', optionC: 'Slowly', optionD: 'The end', correctAnswer: 'optionA', timeLimit: 15 },
    { text: 'What is the lowest female voice type?', optionA: 'Soprano', optionB: 'Mezzo-soprano', optionC: 'Alto', optionD: 'Tenor', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What note is one octave above middle C?', optionA: 'C1', optionB: 'C3', optionC: 'C5', optionD: 'C6', correctAnswer: 'optionC', timeLimit: 20 },
  ],
  'Politics & Government': [
    { text: 'What is the supreme law of the United States?', optionA: 'Bill of Rights', optionB: 'The Constitution', optionC: 'Declaration of Independence', optionD: 'Federalist Papers', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many branches of government does the USA have?', optionA: '2', optionB: '3', optionC: '4', optionD: '5', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the legislative branch of the US government?', optionA: 'The President', optionB: 'Supreme Court', optionC: 'Congress', optionD: 'The Cabinet', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'How many senators does each US state have?', optionA: '1', optionB: '2', optionC: '3', optionD: '4', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is a democracy?', optionA: 'Rule by one person', optionB: 'Rule by the military', optionC: 'Rule by the people', optionD: 'Rule by the wealthy', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the United Nations?', optionA: 'A military alliance', optionB: 'An international organization', optionC: 'A trade agreement', optionD: 'A religious group', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'How long is a US presidential term?', optionA: '2 years', optionB: '4 years', optionC: '6 years', optionD: '8 years', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the head of state in the UK called?', optionA: 'President', optionB: 'Prime Minister', optionC: 'King or Queen', optionD: 'Chancellor', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What amendment abolished slavery in the USA?', optionA: '12th', optionB: '13th', optionC: '14th', optionD: '15th', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is a republic?', optionA: 'A state without a monarch', optionB: 'A state with elected representatives', optionC: 'A state with a king', optionD: 'A military government', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What does "veto" mean?', optionA: 'To approve', optionB: 'To reject', optionC: 'To delay', optionD: 'To discuss', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'Who is the head of the executive branch in the USA?', optionA: 'Speaker of the House', optionB: 'Chief Justice', optionC: 'The President', optionD: 'Vice President', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is NATO?', optionA: 'Trade organization', optionB: 'Military alliance', optionC: 'Environmental group', optionD: 'Human rights group', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'How many members are in the US House of Representatives?', optionA: '100', optionB: '325', optionC: '435', optionD: '535', correctAnswer: 'optionC', timeLimit: 20 },
    { text: 'What system divides power between national and state governments?', optionA: 'Unitary system', optionB: 'Federalism', optionC: 'Confederation', optionD: 'Parliamentary', correctAnswer: 'optionB', timeLimit: 15 },
  ],
  'Travel & Landmarks': [
    { text: 'What country is the Eiffel Tower in?', optionA: 'Italy', optionB: 'Spain', optionC: 'France', optionD: 'England', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What is the largest ocean in the world?', optionA: 'Atlantic', optionB: 'Indian', optionC: 'Arctic', optionD: 'Pacific', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Where are the Pyramids of Giza located?', optionA: 'Libya', optionB: 'Morocco', optionC: 'Egypt', optionD: 'Sudan', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What city is the Statue of Liberty in?', optionA: 'Washington D.C.', optionB: 'Los Angeles', optionC: 'Chicago', optionD: 'New York City', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'What landmark is in Agra, India?', optionA: 'Angkor Wat', optionB: 'Taj Mahal', optionC: 'Petra', optionD: 'Hagia Sophia', correctAnswer: 'optionB', timeLimit: 10 },
    { text: 'What is the Colosseum?', optionA: 'A church', optionB: 'An amphitheater', optionC: 'A palace', optionD: 'A temple', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'Where is Machu Picchu located?', optionA: 'Mexico', optionB: 'Bolivia', optionC: 'Peru', optionD: 'Colombia', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is the longest wall in the world?', optionA: 'Hadrian\'s Wall', optionB: 'Berlin Wall', optionC: 'Great Wall of China', optionD: 'Walls of Babylon', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What landmark is on the island of Alcatraz?', optionA: 'A church', optionB: 'A prison', optionC: 'A castle', optionD: 'A museum', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What country is Petra in?', optionA: 'Egypt', optionB: 'Iraq', optionC: 'Jordan', optionD: 'Turkey', correctAnswer: 'optionC', timeLimit: 15 },
    { text: 'What is Christ the Redeemer?', optionA: 'A painting', optionB: 'A statue', optionC: 'A cathedral', optionD: 'A bridge', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What city is Big Ben located in?', optionA: 'Paris', optionB: 'Rome', optionC: 'London', optionD: 'Berlin', correctAnswer: 'optionC', timeLimit: 10 },
    { text: 'What waterfall is on the border of USA and Canada?', optionA: 'Victoria Falls', optionB: 'Iguazu Falls', optionC: 'Angel Falls', optionD: 'Niagara Falls', correctAnswer: 'optionD', timeLimit: 10 },
    { text: 'Where is the Parthenon located?', optionA: 'Rome', optionB: 'Athens', optionC: 'Istanbul', optionD: 'Cairo', correctAnswer: 'optionB', timeLimit: 15 },
    { text: 'What is the Sydney Opera House known for?', optionA: 'Its design', optionB: 'Its height', optionC: 'Its age', optionD: 'Its size', correctAnswer: 'optionA', timeLimit: 15 },
  ],
}

// Get random questions from the bank for a category
export function getBankQuestions(category: string, count: number): any[] {
  const pool = questionBank[category]

  if (!pool || pool.length === 0) return []

  // Shuffle and pick the requested count
  const shuffled = [...pool].sort(() => Math.random() - 0.5)
  const selected = shuffled.slice(0, Math.min(count, shuffled.length))

  return selected.map((q, i) => ({
    id: `q_bank_${Date.now()}_${i}`,
    text: q.text,
    optionA: q.optionA,
    optionB: q.optionB,
    optionC: q.optionC,
    optionD: q.optionD,
    correctAnswer: q.correctAnswer,
    timeLimit: q.timeLimit,
    order: i,
  }))
}
